# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dis/Documents/pasha/bigramms_corrTable/corrTableGUI/corrTableGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 315)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.download_sheet = QtWidgets.QPushButton(self.groupBox)
        self.download_sheet.setObjectName("download_sheet")
        self.gridLayout_3.addWidget(self.download_sheet, 1, 3, 1, 1)
        self.sheet = QtWidgets.QTextEdit(self.groupBox)
        self.sheet.setMinimumSize(QtCore.QSize(0, 0))
        self.sheet.setMaximumSize(QtCore.QSize(16777215, 25))
        self.sheet.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sheet.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sheet.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sheet.setObjectName("sheet")
        self.gridLayout_3.addWidget(self.sheet, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(self.groupBox)
        self.downloadButton.setMinimumSize(QtCore.QSize(0, 0))
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_3.addWidget(self.downloadButton, 0, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calcButton = QtWidgets.QPushButton(self.groupBox)
        self.calcButton.setObjectName("calcButton")
        self.verticalLayout_4.addWidget(self.calcButton)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_5.addWidget(self.saveButton)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.gridGroupBox = QtWidgets.QGroupBox(self.groupBox)
        self.gridGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.strFin = QtWidgets.QTextEdit(self.gridGroupBox)
        self.strFin.setMaximumSize(QtCore.QSize(16777215, 25))
        self.strFin.setInputMethodHints(QtCore.Qt.ImhNone)
        self.strFin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strFin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strFin.setObjectName("strFin")
        self.gridLayout.addWidget(self.strFin, 1, 1, 1, 1)
        self.strInit = QtWidgets.QTextEdit(self.gridGroupBox)
        self.strInit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.strInit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.strInit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strInit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.strInit.setObjectName("strInit")
        self.gridLayout.addWidget(self.strInit, 1, 0, 1, 1)
        self.strInit_label = QtWidgets.QLabel(self.gridGroupBox)
        self.strInit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.strInit_label.setObjectName("strInit_label")
        self.gridLayout.addWidget(self.strInit_label, 0, 0, 1, 1)
        self.corrCritical = QtWidgets.QTextEdit(self.gridGroupBox)
        self.corrCritical.setMaximumSize(QtCore.QSize(16777215, 25))
        self.corrCritical.setInputMethodHints(QtCore.Qt.ImhNone)
        self.corrCritical.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.corrCritical.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.corrCritical.setObjectName("corrCritical")
        self.gridLayout.addWidget(self.corrCritical, 1, 2, 1, 1)
        self.corrCritical_label = QtWidgets.QLabel(self.gridGroupBox)
        self.corrCritical_label.setAlignment(QtCore.Qt.AlignCenter)
        self.corrCritical_label.setObjectName("corrCritical_label")
        self.gridLayout.addWidget(self.corrCritical_label, 0, 2, 1, 1)
        self.strFin_label = QtWidgets.QLabel(self.gridGroupBox)
        self.strFin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.strFin_label.setObjectName("strFin_label")
        self.gridLayout.addWidget(self.strFin_label, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gridGroupBox, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "corrTable"))
        self.download_sheet.setText(_translate("MainWindow", "Загрузить лист"))
        self.label.setText(_translate("MainWindow", "Имя листа: "))
        self.downloadButton.setText(_translate("MainWindow", "Загрузить файл"))
        self.calcButton.setText(_translate("MainWindow", "Рассчитать"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.strInit_label.setText(_translate("MainWindow", "Начальная строка"))
        self.corrCritical_label.setText(_translate("MainWindow", "corrCritical"))
        self.strFin_label.setText(_translate("MainWindow", "Конечная строка"))

